FORMAT: 1A
HOST: https://domain.tld/api

# Voyager API

# group Algemeen

## Authenticatie

**TODO**

## Redirects

**TODO:** Beschrijf het stukje omtrent redirects in de API.

## Datums

**TODO:** Documenteer het stukje over de datums in de api zoals bv de ISO waarde van de datums.

## Foutmeldingen

**Status codes**

Zoals gebruikelijk gebruiken we standaard HTTP status codes:

| Code | *Beschrijving* |
